name: berry 0.1.0

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build binary
        run: cargo build --release

      - name: Upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: berry-sasha-computer
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          VERSION: ${{ github.ref_name }}
          AWS_MAX_ATTEMPTS: 5
          AWS_RETRY_MODE: adaptive
        run: |
          VERSION=${VERSION#v}
          
          brew install awscli
          
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region auto
          aws configure set default.retry_mode adaptive
          aws configure set default.max_attempts 5
          
          # Add sleep to avoid rate limiting
          sleep 2
          
          for i in {1..3}; do
            echo "Upload attempt $i of 3..."
            if aws s3api put-object \
              --endpoint-url https://$CLOUDFLARE_ACCOUNT_ID.r2.cloudflarestorage.com \
              --bucket $R2_BUCKET \
              --key "berry-${VERSION}-darwin-arm64" \
              --body "target/release/berry" \
              --acl public-read \
              --content-type "$(file -b --mime-type target/release/berry)"; then
              echo "Upload successful!"
              exit 0
            fi
            echo "Upload failed, waiting before retry..."
            sleep $((5 * i))
          done
          
          echo "All upload attempts failed"
          exit 1
