name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build binary
        run: cargo build --release

      - name: Upload to R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: berry-sasha-computer
          VERSION: ${{ github.ref_name }}
        run: |
          # Strip v prefix from version tag
          VERSION=${VERSION#v}
          
          # Install AWS CLI (works with R2)
          brew install awscli
          
          # Configure AWS CLI for R2
          aws configure set aws_access_key_id $R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $R2_SECRET_ACCESS_KEY
          aws configure set default.region auto
          
          # Upload binary
          aws s3 cp target/release/berry \
              s3://$R2_BUCKET/berry-${VERSION}-darwin-arm64 \
              --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
              --acl public-read
              
          # Upload install script
          aws s3 cp install.sh \
              s3://$R2_BUCKET/install.sh \
              --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
              --acl public-read
              
          # Also upload install script as latest
          aws s3 cp install.sh \
              s3://$R2_BUCKET/install \
              --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
              --acl public-read 